name: ngr_neo
version: 0.1.0+1
publish_to: "none"
description: NGR Neo - Liquid Garage OS, Flutter rebuild for Honda Beat FI 2014.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ngr_icon.png
